---

- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined
      - cloudwatch_region is defined
      - cloudwatch_log_group is defined
      - user_info_service_endpoint is defined
      - domain_name is defined
      - aws_bucket is defined
      - aws_default_region is defined
      - aws_secret_access_key is defined
      - aws_access_key_id is defined

- name: Create the files directory
  file:
    path: "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/files"
    state: directory
    mode: 07500

- name: Create app container
  docker_container:
    name: "{{ application_name }}"
    image: "namelivia/{{ application_name }}:latest"
    memory: "200MB"
    pull: true
    cleanup: true
    restart_policy: "always"
    log_driver: "awslogs"
    log_options:
      awslogs-region: "{{ cloudwatch_region }}"
      awslogs-group: "{{ cloudwatch_log_group }}"
      awslogs-stream: "{{ application_name }}"
    networks:
      - name: "pomerium"
    exposed_ports:
      - "80"
    env:
      USER_INFO_SERVICE_ENDPOINT: "{{ user_info_service_endpoint }}"
      AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
      AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
      AWS_DEFAULT_REGION: "{{ aws_default_region }}"
      AWS_BUCKET: "{{ aws_bucket }}"
      DOMAIN_NAME: "{{ domain_name }}"
      VIRTUAL_HOST: "{{ domain_name }}"
      VIRTUAL_PATH: "{{ subpath }}"
      VIRTUAL_DEST: "/"
      VIRTUAL_PORT: "80"
